### ISSUE TITLE
Research: GH Actions + Dependabot for Previews

### ISSUE THREAD

**Issue by JeromeFitz** [JeromeFitz/websites#861]
Can we allow `dependabot` deploys to Preview?

- Add a `step` in GitHub Actions to determine if the initiator is `dependabot`
- Check out the fork as an inline branch
- Pass _that_ branch as acceptable

This should still be locked down to not accepting others at the moment.

**Comment by JeromeFitz** [comment]
Code has been updated to check against specific github actors `jeromefitz|dependabot|dependabot[bot]` which is okay. Not good, definitely not great.

You can now [add secrets to dependabot](https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/managing-encrypted-secrets-for-dependabot) which may null and void all of this, heh.

**Comment by BotJerome** [comment]
🤖  `Good enough for now.` 🤖
